In [1]:
import numpy as np

In [3]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [5]:
# numpy를 이용하여 1차원 배열로 변형하기 - 배열의 type이 같아야 한다

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [6]:
# 배열의 크기 확인 - shape에 () 사용하지 않는다
arr1.shape

(5,)

In [7]:
# 2차원 List
data2 = [
         [1,2,3,4],
         [5,6,7,8]
        ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2.shape

(2, 4)

In [15]:
# 0으로 구성된 1차원 배열 생성
np.zeros([3, 5, 2]) # 3은 페이지 번호

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
# 1로만 구성된 배열생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [19]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# 숫자 8로 구성된 3행 5열 배열 생성
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [22]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr1.dtype

dtype('float64')

In [27]:
arr3 = np.array([1,2,3,4,5],dtype=np.int64 )
arr3.dtype
arr3

array([1, 2, 3, 4, 5])

In [28]:
# data type을 변경
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [29]:
float_arr1

array([1., 2., 3., 4., 5.])

In [32]:
# 연산
arr1 = np.array([
                [1,2,3],
                [4,5,6]
                ], dtype=np.float64)
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr2 = np.array([
                [7,8,9],
                [10,11,12]
                ], dtype=np.float64)
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [35]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [36]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [37]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [38]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [39]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [41]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5] # 행렬 인덱스

5

In [44]:
arr[5:9]

array([5, 6, 7, 8])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

# 2차원 배열

In [84]:
arr2d = np.array([
                 [1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [52]:
arr2d.dtype

dtype('int64')

In [ ]:
arr2d[2,:]

In [77]:
# 1에서 2번열의 자료 출력
arr2d[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [75]:
# 0, 1 열의 자료 출력
arr2d[:,:2]


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [80]:
# 1행2열의 자료 출력
arr2d[1,2]

7

In [86]:
arr2d[:2,1:3]=0  # start index : stop index, stop index는 포함하지 않는다 1:3 -> 1,2만 포함
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수 발생
- rand : 0부터 1사이의 균일 분포
- randn : 가우시안 표준 정규 분포
- randint : 균일 분포의 정수 난수

### Boolean Indexing

In [141]:
names = np.array(["Charles", "Kenny", "Hayoung", "Charles", "Hayoung", "Kenny", "Kenny"])
data = np.random.randn(7, 4)

In [142]:
names  # <U7

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [143]:
data

array([[ 0.23737106,  0.51775676,  1.1426987 , -1.37841408],
       [-0.28850718,  0.22830646, -0.53657215,  0.17660623],
       [-0.48746247, -0.90154075, -0.00848294, -1.92364213],
       [ 1.01571704, -0.04522641, -0.3379096 ,  1.02967685],
       [-0.28434606,  0.10178291, -0.86449729, -0.66748343],
       [ 1.52552901,  0.06842216, -0.40957784,  0.14083074],
       [-0.88518533,  2.23980535, -0.67809432, -1.30486746]])

In [144]:
# Mask를 이용한 추출
names == "Charles"
data[names == "Charles", :] # True 행번호로 가져온다

array([[ 0.23737106,  0.51775676,  1.1426987 , -1.37841408],
       [ 1.01571704, -0.04522641, -0.3379096 ,  1.02967685]])

In [145]:
data[(names == "Charles") | (names == "Kenny"), :]

array([[ 0.23737106,  0.51775676,  1.1426987 , -1.37841408],
       [-0.28850718,  0.22830646, -0.53657215,  0.17660623],
       [ 1.01571704, -0.04522641, -0.3379096 ,  1.02967685],
       [ 1.52552901,  0.06842216, -0.40957784,  0.14083074],
       [-0.88518533,  2.23980535, -0.67809432, -1.30486746]])

In [146]:
data[:]

array([[ 0.23737106,  0.51775676,  1.1426987 , -1.37841408],
       [-0.28850718,  0.22830646, -0.53657215,  0.17660623],
       [-0.48746247, -0.90154075, -0.00848294, -1.92364213],
       [ 1.01571704, -0.04522641, -0.3379096 ,  1.02967685],
       [-0.28434606,  0.10178291, -0.86449729, -0.66748343],
       [ 1.52552901,  0.06842216, -0.40957784,  0.14083074],
       [-0.88518533,  2.23980535, -0.67809432, -1.30486746]])

In [147]:
data[:, 3]

array([-1.37841408,  0.17660623, -1.92364213,  1.02967685, -0.66748343,
        0.14083074, -1.30486746])

In [148]:
# data의 4번째 열 값중 0보다 작은 것의 mask 만들기
data[data[:, 3] < 0, :] # 조건만들고 감싸서 사용

array([[ 0.23737106,  0.51775676,  1.1426987 , -1.37841408],
       [-0.48746247, -0.90154075, -0.00848294, -1.92364213],
       [-0.28434606,  0.10178291, -0.86449729, -0.66748343],
       [-0.88518533,  2.23980535, -0.67809432, -1.30486746]])

In [149]:
data[:]

array([[ 0.23737106,  0.51775676,  1.1426987 , -1.37841408],
       [-0.28850718,  0.22830646, -0.53657215,  0.17660623],
       [-0.48746247, -0.90154075, -0.00848294, -1.92364213],
       [ 1.01571704, -0.04522641, -0.3379096 ,  1.02967685],
       [-0.28434606,  0.10178291, -0.86449729, -0.66748343],
       [ 1.52552901,  0.06842216, -0.40957784,  0.14083074],
       [-0.88518533,  2.23980535, -0.67809432, -1.30486746]])

In [152]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
data[data[:, 3] < 0, :] = 0
data


array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.28850718,  0.22830646, -0.53657215,  0.17660623],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.01571704, -0.04522641, -0.3379096 ,  1.02967685],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.52552901,  0.06842216, -0.40957784,  0.14083074],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [154]:
# 정렬
arr = np.random.rand(8)
arr

array([0.39143833, 0.18431122, 0.38799089, 0.30118545, 0.64285294,
       0.78566825, 0.08061964, 0.83931869])

In [155]:
# 오름차순 정렬
np.sort(arr)

array([0.08061964, 0.18431122, 0.30118545, 0.38799089, 0.39143833,
       0.64285294, 0.78566825, 0.83931869])

In [156]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.83931869, 0.78566825, 0.64285294, 0.39143833, 0.38799089,
       0.30118545, 0.18431122, 0.08061964])

In [158]:
arr = np.random.rand(5, 3)
arr

array([[0.85043874, 0.50754696, 0.79778463],
       [0.04688221, 0.15919779, 0.69613279],
       [0.51323931, 0.84633601, 0.01424219],
       [0.7611337 , 0.58597887, 0.08946751],
       [0.76301459, 0.91506423, 0.50353945]])

In [159]:
np.sort(arr, axis=0) # 0 : 열방향


array([[0.04688221, 0.15919779, 0.01424219],
       [0.51323931, 0.50754696, 0.08946751],
       [0.7611337 , 0.58597887, 0.50353945],
       [0.76301459, 0.84633601, 0.69613279],
       [0.85043874, 0.91506423, 0.79778463]])

In [160]:
np.sort(arr, axis=1) # 1 : 행방향

array([[0.50754696, 0.79778463, 0.85043874],
       [0.04688221, 0.15919779, 0.69613279],
       [0.01424219, 0.51323931, 0.84633601],
       [0.08946751, 0.58597887, 0.7611337 ],
       [0.50353945, 0.76301459, 0.91506423]])

In [162]:
np.sort(arr, axis=1)[:,::-1] # 1 : 행방향

array([[0.85043874, 0.79778463, 0.50754696],
       [0.69613279, 0.15919779, 0.04688221],
       [0.84633601, 0.51323931, 0.01424219],
       [0.7611337 , 0.58597887, 0.08946751],
       [0.91506423, 0.76301459, 0.50353945]])

In [163]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape

In [181]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [182]:
arr.shape

(8,)

In [183]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2, 4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [184]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2)) #(page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [185]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1,1) # 데이터 갯수를 정할 수 없을 때 -1, 1은 차원수 표시 명시적으로 표시한다
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [188]:
arr4 = arr2.reshape(-1)  
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [189]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])